### ISSUE TITLE
YAML highlighting doesn't work as expected

### ISSUE THREAD

**Issue by Altair-Bueno** [sbarex/SourceCodeSyntaxHighlight#104]
Check the difference between Visual Studio Code and SCSH. Something is odd with YAML highlighting. This happens both on RTF and HTML engines. I already tried updating with no success

![image](https://user-images.githubusercontent.com/67512202/128535593-4cc5a3eb-ebe1-40c2-9a4b-7d641746e173.png)

<details>

```yaml

template_folder: template/
targer_folder: out/
static_resources: 
    - res/
templates:
    - style.css 
    - index.html
replace_dic:
    BREAKPOINT_CSS_FOOTER: 650px
    WEBSITE_NAME: "Altair Bueno"
    WEBSITE_URL: "https://altair-bueno.github.io/"
    PROFILEPICTURE: "https://avatars.githubusercontent.com/u/67512202?v=4"
    STATIC_GENERATED: "Test string for comment"
    DESCRIPTION: "Altair's business card and contact info"
    AUTHOR_NAME: "Altair Bueno"
    GITHUB_TITLE: "Check Altair's projects on GitHub"
    GITHUB_URL: "https://github.com/Altair-Bueno"
    LINKEDIN_TITLE: "Find me in Linkedin"
    LINKEDIN_URL: "https://example.org"
    MAIL_TITLE: "Contact me"
    MAIL_URL: "mailto:business.altair.bueno@outlook.com"
    PROFILEPICTURE_TITLE: "Check the source code"
    PROFILEPICTURE_URL: "https://github.com/Altair-Bueno/altair-bueno.github.io"
    MAIN_BODY_CONTENT: |
        <h1>Lorem ipsum dolor sit amet</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
                incididunt ut labore et dolore magna aliqua. Elit scelerisque mauris pellentesque 
                pulvinar. Lorem donec massa sapien faucibus et molestie ac feugiat. A erat nam at 
                lectus. Nunc non blandit massa enim nec dui nunc. Diam vel quam elementum pulvinar.
            </p>
    TEMPLATE_CREATOR: |
        <div>
            Template made with ❤️ by <a class="footer_link" href="https://github.com/Altair-Bueno">Altair Bueno</a>
        </div>

```

</details>

**Comment by sbarex** [comment]
It must be a highlight bug. [I reported it to the author](https://gitlab.com/saalen/highlight/-/issues/190).

**Comment by sbarex** [comment]
Try release 2.1.11.

**Comment by Altair-Bueno** [comment]
It now works as expected. Thanks!

**Comment by normanius** [comment]
@sbarex 

I'm working with the latest release (2.1.15). The YAML highlighting seems broken again (see the highlighting of "defaults_clinical" below). I've also attached the entire YAML file.

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/11406002/195959121-75e7c16d-28bb-424c-815a-f5f248dd484a.png">


<details>
```yaml
################################################################################
# OPUS MAGNUM SERIES: CUTS-BASED (cutToShow)
################################################################################

################################################################################
# CONTROLS
################################################################################
# Substitution variables. To reference a variable: {{variableName}}.
variables :
  # Sources.
  aneux : true

  meshSubDir : 'remeshed/area-005'  # Choose available mesh resolution
  perSource : true                  # Sort per data source
  sortBy : 'dataset'                # 'random', 'dataset', 'attribute'
  sortKey : 'location'              # if sortBy == 'attribute'

  # Items.
  showAneurysms : true
  showContext : true
  contextAlpha : 0.1

################################################################################
# Convenience flags to globally enable/disable sources.
defaults_aneux : &defaults_aneux
  enabled : '{{aneux}}'
  collectionId : 'aneux'

# Defaults.
defaults_cut : &defaults_cut
  #pattern : '.*\.vtp'
  pattern : '.*(?:cut1|cut2)\.vtp'  # Speed: exclude as many files as possible
  nameCapture : null                # Equivalent to '(.*)'
  infoCaptures :
    # Capture the cutType as attribute.
    cutType : '.*_(dome|cut0|cut1|cut2|ninja)'
  primary : true
  enabled : true

defaults_context : &defaults_context
  pattern : '.*\.vtp'
  nameCapture : null                # Equivalent to '(.*)'
  matchMode : 'startswith'
  ensureCount : 1

defaults_camera : &defaults_camera
  purpose : 'camera'
  nameMode : postfix
  nameCapture : '_cuts'
  matchCapture : '(.*)_.*'

defaults_clinical: &defaults_clinical
  nameCapture : '(.*)'
  matchCapture : '(.*)_.*'
  dataFileMode : true
  dataFileProps :
    indexCol : 'dataset'
    dataCols : ['location', 'ruptured']

context : &enable_context
  enabled : '{{showContext}}'
  primary : false

streams :
  ##############################################################################
  # ANEUXDB
  ##############################################################################
  - id : 'aneux-cut'
    root : '${ANEUX_DATA}/models/aneurysms/{{meshSubDir}}'
    <<: *defaults_cut
    <<: *defaults_aneux
  - id : 'aneux-context'
    root : '${ANEUX_DATA}/models/vessels/remeshed/area-005'
    pattern : '.*\.vtp'
    <<: *defaults_context
    <<: *defaults_aneux
    <<: *enable_context

################################################################################
# ATTRIBUTES
################################################################################
attributes :
  # Camera info
  - id : 'aneux-camera'
    root : '${ANEUX_DATA}/models/cuts/planar/*.json'
    <<: *defaults_camera
    <<: *defaults_aneux

################################################################################
# ITEMS
################################################################################
items :
  aneurysms : &aneurysms
    color : 'white'
    opacity : 1.0
    visible : '{{showAneurysms}}'
  context : &context
    color : 'white'
    opacity : '{{contextAlpha}}'
    visible : '{{showContext}}'

  aneux-cut :
    <<: *aneurysms
  aneux-context :
    <<: *context

################################################################################
# FILTERING
################################################################################
datasets :
  nDatasetsMax : null
  perCollection : '{{perSource}}'
  ascending : true
  # sortBy : 'dataset'   # Sort datasets by their id
  sortBy : '{{sortBy}}'
  sortKey : '{{sortKey}}'
  random :
    seed : null
    preserve : true

  # Possibility 1:
  #   - Use the clinical tables containing data per cut.
  #   - Construct datasetIds by joining indexCols 'dataset' and 'cut-type'.
  #   - Filter only the lines where cutToShow has value 'yes'.
  filterFile :
    path :
      - '${ANEUX_DATA}/data/clinical-per-cut.csv'
    nameCapture : '(.*)'
    multiCapture : false
    indexCol : ['dataset', 'cut-type']
    indexColJoin : '{0}_{1}' # Join pattern: <dataset>_<cut-type>
    include:
      cutToShow: ['yes', 'Yes']

  # Possibility 2:
  #   - Use the clinical tables with data per case
  #   - Construct datasetIds by joining indexCols 'dataset' and 'cutToShow'.
  filterFile :
    path :
      - '${ANEUX_DATA}/data/clinical.csv'
    indexCol : ['dataset', 'cutToShow']
    indexColJoin : '{0}_{1}' # Join pattern: <dataset>_<cut-type>

  # This hides the cut-type suffix: datasetId_cutId => datasetId
  # The cut-type is still captured through an "infoCapture", see above.
  renameIds :
    capture : '(.*)_.*'       # <identifier>_<cutType>
    template : '{0}'          # <identifier>

```
</details>
