### ISSUE TITLE
The light/dark scheme doesn't change automatically

### ISSUE THREAD

**Issue by dingyiyi0226** [sbarex/SourceCodeSyntaxHighlight#214]
If I change the system appearance to light/dark scheme, the quicklook content doesn't change.
It only works if I relaunch the folder.

Dark scheme:
<img width="672" alt="Screen Shot 2022-12-15 at 13 01 12" src="https://user-images.githubusercontent.com/35497159/207776764-53595acb-3a9a-49b4-9507-5882756b6731.png">

Change to light scheme:
<img width="692" alt="Screen Shot 2022-12-15 at 13 01 20" src="https://user-images.githubusercontent.com/35497159/207776772-c55d220a-1731-4cda-8174-c92b6266e5dd.png">

- macOS Monterey 12.4

**Comment by hazarek** [comment]
Paste the following CSS code here. (Custom CSS Style window)
<img width="705" alt="Ekran Resmi 2022-12-15 11 12 42" src="https://user-images.githubusercontent.com/36481442/207807784-2ac6adbf-f71b-4421-b1b2-15c088192180.png">

```css
:root {
  --default_text: #2e2e2e;
  --hl_Background: #F6F8FA ;
  --hl_Number: #005cc5 ;
  --hl_Escape: #032f62 ;
  --hl_String: #032f62 ;
  --hl_String_Pre_Processor: #549ef1 ;
  --hl_Block_Comment: #6a737d ;
  --hl_Line_Comment: #6a737d ;
  --hl_Pre_Processor: #d73a49 ;
  --hl_Line_Number:  #52565C ;
  --hl_Operator: #032f62 ;
  --hl_Interpolation:  #79c0ff ;
  --hl_Keyword-1: #d73a49 ;
  --hl_Keyword-2: #d73a49 ;
  --hl_Keyword-3: #24292e ;
  --hl_Keyword-4: #6f42c1 ;
  --hl_Keyword-5: #d73a49 ;
  --hl_Keyword-6: #d73a49 ;
}

@media (prefers-color-scheme: dark) {
  :root {
      /* Base Light */
  --default_text: #e3e3e3;
  --hl_Background: #2d333b ;
  --hl_Number: #79c0ff ;
  --hl_Escape: #a5d6ff ;
  --hl_String: #549ef1 ;
  --hl_String_Pre_Processor: #549ef1 ;
  --hl_Block_Comment: #8b949e ;
  --hl_Line_Comment: #8b949e ;
  --hl_Pre_Processor: #FF7B72 ;
  --hl_Line_Number:  #52565C ;
  --hl_Operator: #79c0ff ;
  --hl_Interpolation:  #79c0ff ;
  --hl_Keyword-1: #FF7B72 ;
  --hl_Keyword-2: #FF7B72 ;
  --hl_Keyword-3: #c9d1d9 ;
  --hl_Keyword-4: #eea8ff ; 
  --hl_Keyword-5: #FF7B72 ;
  --hl_Keyword-6: #FF7B72 ;
  }
}
/*Syntax Highlight*/

body.hl	{ background-color: var(--hl_Background);} /* Canvas */
pre.hl	{ color: var(--default_text);} /* Default text */
pre.hl	{ background-color: var(--hl_Background);} /* Default content BG*/
.hl.num	{ color: var(--hl_Number); font-weight: normal;} /* Numbers */
.hl.esc	{ color: var(--hl_Escape); font-weight: normal;} /* Escape */
.hl.sng	{ color: var(--hl_String); font-weight: normal;} /* String */
.hl.pps { color: var(--hl_String_Pre_Processor); font-weight: normal;} /* Preprocessor */
.hl.slc { color: var(--hl_Line_Comment); font-weight: normal;}	/* Single line comment */
.hl.com { color: var(--hl_Block_Comment); font-weight: normal;}	/* Multi line comment */
.hl.ppc { color: var(--hl_Pre_Processor); font-weight: normal;}	/* Post-processor */
.hl.opt { color: var(--hl_Operator); font-weight: normal;}	/* Operator */
.hl.ipl { color: var(--hl_Interpolation); font-weight: normal;}	/* Interpolation */
.hl.lin { color: var(--hl_Line_Number); font-weight: normal;}	/* Line numbers */
.hl.kwa { color: var(--hl_Keyword-1); font-weight: normal;} /* Keyword a */
.hl.kwb { color: var(--hl_Keyword-2); font-weight: normal;} /* Keyword b */
.hl.kwc { color: var(--hl_Keyword-3); font-weight: normal;} /* Keyword c */
.hl.kwd { color: var(--hl_Keyword-4); font-weight: normal;} /* Keyword d */
.hl.kwe { color: var(--hl_Keyword-5); font-weight: normal;} /* Keyword e */
.hl.kwf { color: var(--hl_Keyword-6); font-weight: normal;} /* Keyword f */

/* hl.hvr {}	LS Hover
hl.err {}	LS Syntax Error
hl.sta {}	LS Type
hl.stb {}	LS Class
hl.stc {}	LS Struct
hl.std {}	LS Interface
hl.ste {}	LS Parameter
hl.stf {}	LS Variable
hl.stg {}	LS Enum Member
hl.sth {}	LS Function
hl.sti {}	LS Method
hl.stj {}	LS Keyword
hl.stk {}	LS Number
hl.stl {}	LS Regexp
hl.stm {}	LS Operator */
```

If you want, you can edit the colors with a Code Editor (VS Code). Edit this CSS -> `~/Library/Application Support/Syntax Highlight/Styles/global.css`

<img width="591" alt="Ekran Resmi 2022-12-15 11 09 31" src="https://user-images.githubusercontent.com/36481442/207808683-b84e72a0-a1eb-4ff4-9064-06bb93770030.png">

Result: The theme now changes automatically:

https://user-images.githubusercontent.com/36481442/207809050-b20597fa-968e-4be6-9a86-096e7bc3a0e7.mov
