### ISSUE TITLE
Colons in strings are not parsed correctly in YAML files

### ISSUE THREAD

**Issue by dnicolson** [sbarex/SourceCodeSyntaxHighlight#241]
The following YAML:
```
AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    CloudWatchAlarm:
        Type: "AWS::CloudWatch::Alarm"
        Properties:
            AlarmName: "Alarm"
```

Results in:
<img width="720" alt="Screenshot 2023-05-19 at 21 14 38" src="https://github.com/sbarex/SourceCodeSyntaxHighlight/assets/2276355/905f973a-aa07-42fe-95a4-33b924333006">
